import React from 'react';
import { ArrowLeft } from 'lucide-react';

interface TermsViewProps {
  onBack: () => void;
}

export const TermsView: React.FC<TermsViewProps> = ({ onBack }) => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <button 
        onClick={onBack} 
        className="flex items-center text-slate-500 hover:text-slate-900 mb-8 transition-colors"
      >
        <ArrowLeft size={16} className="mr-2" /> Back
      </button>

      <div className="prose prose-slate max-w-none">
        <h1>Terms of Service</h1>
        <p className="text-slate-500 text-lg mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <h2>1. Agreement to Terms</h2>
        <p>By accessing or using Greenli8, you agree to be bound by these Terms of Service.</p>

        <h2>2. Use of Service</h2>
        <p>You agree to use our service only for lawful purposes. You must not use our AI to generate harmful, illegal, or abusive content.</p>

        <h2>3. AI Disclaimer</h2>
        <p>Our validation reports are generated by Artificial Intelligence. They are for informational purposes only and should not be considered professional financial or legal advice. We make no guarantees regarding the success of any business idea.</p>

        <h2>4. Refunds</h2>
        <p>Due to the cost of AI generation, we generally do not offer refunds for used credits. If you believe there was a technical error, please contact support.</p>

        <h2>5. Limitation of Liability</h2>
        <p>Greenli8 shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.</p>
      </div>
    </div>
  );
};